### ISSUE TITLE
Double Entry

### ISSUE THREAD

**Issue by 868jjm** [rafaelurben/django-kmuhelper#90]
Simple double entry for basic general accounting principles adherence would be a great feature to add.

**Comment by rafaelurben** [comment]
Hey @868jjm! Thank you for submitting this issue!

I'm very sorry, but I have some trouble understanding what exactly you mean by that. 
Could you please clarify this a little bit? Thanks!

**Comment by 868jjm** [comment]
In accounts for example when a liability is paid the amount enters expenses and is the liability is removed. This is called a double entry accounting system. It can be done manually but it would be perfect if you can get it automatically.

**Comment by rafaelurben** [comment]
I'll look into it if I find some time! Thanks for explaining!

**Comment by rafaelurben** [comment]
Hey @868jjm

I decided that I won't include this feature in the kmuhelper. The kmuhelper isn't made for very professional purposes and I think this feature isn't in the intended scope of this app. 
I am aware that I put accounting in the description and tags of this repository, but I realized that this isn't really accurate because the intended purpose (at the moment) is just managing orders and customers. I'm probably going to update that in the future.

But thank you anyway for your issue!
